In [111]:
import numpy as np
from sympy import *
from sympy.abc import alpha, beta, theta,omega,delta
init_printing()
from qutip import *

# Two-transmons + cavity

In [57]:
N, M =3,4
b1 = destroy(N)
b2 = destroy(N)
c = destroy(M)
Ib = qeye(N)
Ic = qeye(M)
Del1, Del2, del1, del2 = -0.9, -1, -0.3,-0.3
g1, g2 = 0.100, 0.100

# This gives Eq.(2.11) alike in Magesan paper.
H1 = Del1*tensor(b1.dag()*b1, Ib, Ic) + del1/2*tensor(b1.dag()*b1 * (b1.dag()*b1 - Ib), Ib, Ic)
H2 = Del2*tensor(Ib, b2.dag()*b2, Ic) + del2/2*tensor(Ib, b2.dag()*b2 * ( b2.dag()*b2 - Ib), Ic)
H3 = g1*(tensor(b1.dag(), Ib, c) + tensor(b1, Ib, c.dag())) + g2*(tensor(Ib, b2.dag(),  c) + tensor(Ib, b2, c.dag()))
H = H1 + H2 + H3

# This gives Eq.(2.6) in Magesan paper.
# H1 = Del1*tensor(Ic, b1.dag()*b1, Ib) + del1/2*tensor(Ic, b1.dag()*b1 * (b1.dag()*b1 - Ib), Ib)
# H2 = Del2*tensor(Ic, Ib, b2.dag()*b2) + del2/2*tensor(Ic,Ib, b2.dag()*b2 * ( b2.dag()*b2 - Ib))
# H3 = g1*(tensor(c, b1.dag(), Ib) + tensor(c.dag(), b1, Ib)) + g2*(tensor(c, Ib, b2.dag()) + tensor(c.dag(), Ib, b2))
# H = H1 + H2 + H3


In [63]:
sympy.SparseMatrix(np.round((H)[:, 0:18],1))

Matrix([
[0,   0,   0,   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
[0,   0,   0,   0,  0.1,    0,    0,    0,    0,    0,    0,    0,  0.1,    0,    0,    0,    0,    0],
[0,   0,   0,   0,    0,  0.1,    0,    0,    0,    0,    0,    0,    0,  0.1,    0,    0,    0,    0],
[0,   0,   0,   0,    0,    0,  0.2,    0,    0,    0,    0,    0,    0,    0,  0.2,    0,    0,    0],
[0, 0.1,   0,   0, -1.0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
[0,   0, 0.1,   0,    0, -1.0,    0,    0,  0.1,    0,    0,    0,    0,    0,    0,    0,  0.1,    0],
[0,   0,   0, 0.2,    0,    0, -1.0,    0,    0,  0.2,    0,    0,    0,    0,    0,    0,    0,  0.1],
[0,   0,   0,   0,    0,    0,    0, -1.0,    0,    0,  0.2,    0,    0,    0,    0,    0,    0,    0],
[0,   0,   0,   0,    0,  0.1,    0,    0, -2.3,    0,    0,    0,    0,    0,    0,    0,    0,    0],
[0,   0,   0,   0,    0,    0,  0.2,    0,    0, -2.3, 

In [86]:
a=destroy(5)

In [94]:
a+a.dag()
# -1j*a+1j*a.dag()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  1.  0.  0.  0. ]
 [1.  0.  1.4 0.  0. ]
 [0.  1.4 0.  1.7 0. ]
 [0.  0.  1.7 0.  2. ]
 [0.  0.  0.  2.  0. ]]

In [95]:
a.dag()*a
a.dag()*a *(a.dag()*a-qeye(5))

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.]
 [ 0.  0.  0.  6.  0.]
 [ 0.  0.  0.  0. 12.]]

# Two-level qubit + CR

In [113]:
J = Symbol('J')
H_R = Matrix([[0,0,omega/2,0],[0,0,J,omega/2],[omega/2,J,delta,0],[0,omega/2,0,delta]])
H_R

⎡      ω   ⎤
⎢0  0  ─  0⎥
⎢      2   ⎥
⎢          ⎥
⎢         ω⎥
⎢0  0  J  ─⎥
⎢         2⎥
⎢          ⎥
⎢ω         ⎥
⎢─  J  δ  0⎥
⎢2         ⎥
⎢          ⎥
⎢   ω      ⎥
⎢0  ─  0  δ⎥
⎣   2      ⎦

In [129]:
N1 = sqrt(2 + 2*omega**2/(2*delta**2+omega**2 + 2*delta*sqrt(delta**2+omega**2)))
N2 = sqrt(2 + 2*omega**2/(2*delta**2+omega**2 - 2*delta*sqrt(delta**2+omega**2)))
A1 = sqrt(2)/N1
A2 = sqrt(2)/N2
B1 = -sqrt(2)*omega/(delta + sqrt(delta**2+omega**2)) / N1
B2 = -sqrt(2)*omega/(delta - sqrt(delta**2+omega**2)) / N2

T = Matrix([[A1,0,A2,0]
           ,[0,A1,0,A2]
           ,[B1,0,B2,0]
           ,[0,B1,0,B2]])
T

⎡                             √2                                              
⎢         ─────────────────────────────────────────                           
⎢                __________________________________                           
⎢               ╱                2                                            
⎢              ╱              2⋅ω                                             
⎢             ╱   ──────────────────────────── + 2                            
⎢            ╱                  _________                                     
⎢           ╱        2         ╱  2    2     2                                
⎢         ╲╱      2⋅δ  + 2⋅δ⋅╲╱  δ  + ω   + ω                                 
⎢                                                                             
⎢                                                                             
⎢                             0                                         ──────
⎢                                                   

In [144]:
simplify(T)

⎡                            √2                                               
⎢         ────────────────────────────────────────                            
⎢                   ______________________________                            
⎢                  ╱             _________                                    
⎢                 ╱     2       ╱  2    2     2                               
⎢                ╱     δ  + δ⋅╲╱  δ  + ω   + ω                                
⎢         2⋅    ╱    ────────────────────────────                             
⎢              ╱                   _________                                  
⎢             ╱         2         ╱  2    2     2                             
⎢           ╲╱       2⋅δ  + 2⋅δ⋅╲╱  δ  + ω   + ω                              
⎢                                                                             
⎢                                                                             
⎢                             0                     

In [145]:
simplify(transpose(T)*H_R*T) 
# Digonal blocks match with Eq.3.12 and 3.13, but off-diagonal blocks are not zero, why?....

⎡                                  _________ ⎛          _________    2⎞       
⎢                             2   ╱  2    2  ⎜ 2       ╱  2    2    ω ⎟       
⎢                           -ω ⋅╲╱  δ  + ω  ⋅⎜δ  + δ⋅╲╱  δ  + ω   + ──⎟       
⎢                                            ⎝                      2 ⎠       
⎢                          ──────────────────────────────────────────────     
⎢                                            2                                
⎢                          ⎛       _________⎞  ⎛          _________     ⎞     
⎢                          ⎜      ╱  2    2 ⎟  ⎜ 2       ╱  2    2     2⎟     
⎢                          ⎝δ + ╲╱  δ  + ω  ⎠ ⋅⎝δ  + δ⋅╲╱  δ  + ω   + ω ⎠     
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢                                                   

# Going from effective two-transmon Hamiltonian to effective diagonal Hamiltonian

Q: what is U in Eq.4.1?

In [140]:
simplify?