In [15]:
%matplotlib
import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import h,e
from itertools import product

Using matplotlib backend: Qt5Agg


In [32]:
M = np.array([[-1.45, 0.46],[1.44, 1.3]]) # pH
M_inverse = np.linalg.inv(M)

In [68]:
Phi_T = np.linspace(-1, 1, 100) * (h/2/e)/1e-12  
Phi_B = np.linspace(-1, 1, 100) * (h/2/e)/1e-12

Phi_T_B = [(phi_t, phi_b) for phi_t in Phi_T for phi_b in Phi_B]
    
I_T = [ np.matmul(M_inverse, np.array(x))[0] for x in Phi_T_B ]
I_B = [ np.matmul(M_inverse, np.array(x))[1] for x in Phi_T_B ]

print(f'max. current of top bias line = {np.max(I_T)/1e-3:.3f} mA')
print(f'max. current of bottom bias line = {np.max(I_B)/1e-3:.3f} mA')

max. current of top bias line = 1.429 mA
max. current of bottom bias line = 2.346 mA


In [72]:
np.matmul(M_inverse, np.array([-1,-1])*(h/2/e)/1e-12)

array([ 0.00068186, -0.00234594])

In [78]:
plt.imshow(np.array(I_T).reshape(100,100))

In [77]:
plt.imshow(np.array(I_B).reshape(100,100))

In [23]:
product?

In [52]:
N= np.array([[1,2],[3,4]])
N

array([[1, 2],
       [3, 4]])

In [55]:
np.matmul(N, np.array([1,2]))

array([ 5, 11])